services:
  - type: web
    name: cloud
    env: static
    buildCommand: echo "const MAPBOX_TOKEN = '$MAPBOX_TOKEN';" > config.js
    staticPublishPath: .
    envVars:
      - key: MAPBOX_TOKEN
        sync: false
